config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#index"

  resources :pages, :only => [:index]

  resources :members, :only => [:index]

  resources :reviews, :only => [:index]

  resources :genres do
    resources :artists, :only => [:create, :new]
  end

  resources :artists, :except => [:create, :new] do
    resources :members, :except => [:index]
    resources :reviews, :except => [:index]
  end


end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :genre
  has_many :members
  has_many :reviews
  validates :name, presence: true

  default_scope {
    order('name ASC')
  }
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :artists
  validates :name, presence: true

  default_scope {
    order('name DESC')
  }
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :artist
  validates :first_name, :last_name, :instrument, :age, :time_in_band, presence: true

  default_scope {
    order('first_name ASC')
  }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :artist
  validates :author, :content, presence: true

  default_scope {
    order('created_at DESC')
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @genre = Genre.find(params[:genre_id])
    @artist = @genre.artists.new
  end

  def create
    @genre = Genre.find(params[:genre_id])
    @artist = @genre.artists.new(artist_params)
    if @artist.save
      redirect_to genre_path(@artist.genre)
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
    @genre = @artist.genre
  end

  def destroy
    artist = Artist.find(params[:id])
    @genre = artist.genre
    artist.members.each do |member|
      member.destroy
    end
    artist.reviews.each do |review|
      review.destroy
    end
    artist.destroy
    redirect_to genre_path(@genre)
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      render :edit
    end
  end

private
  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path
    else
      render :new
    end
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.artists.each do |artist|
      artist.destroy
    end
    genre.destroy
    redirect_to genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genres_path
    else
      render :edit
    end
  end

private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @member = Member.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @member = @artist.members.new(member_params)
    if @member.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:artist_id])
    @member = Member.find(params[:id])
  end

  def destroy
    member = Member.find(params[:id])
    @artist = Artist.find(params[:artist_id])
    member.destroy
    redirect_to artist_path(@artist)
  end

  def edit
    @member = Member.find(params[:id])
    @artist = Artist.find(params[:artist_id])
  end

  def update
    @member = Member.find(params[:id])
    @artist = Artist.find(params[:artist_id])
    if @member.update(member_params)
      redirect_to artist_member_path(@artist, @member)
    else
      render :edit
    end
  end

private
  def member_params
    params.require(:member).permit(:first_name, :last_name, :instrument, :age, :time_in_band)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    render template: "home"
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @review = Review.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @review = @artist.reviews.new(review_params)
    if @review.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def destroy
    @artist = Artist.find(params[:artist_id])
    review = Review.find(params[:id])
    review.destroy
    redirect_to artist_path(@artist)
  end

private
  def review_params
    params.require(:review).permit(:author, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= render "layouts/errors", :object => @artist %>

<%= form_for [@genre, @artist] do |f| %>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit <%= @artist.name %></h1>

<%= render "form" %>

app/views/artists/index.html.erb
<h1>Artists!</h1>

<h3>Here are all of the artists!</h3>

<div class="row">
  <% @artists.each do |artist| %>
    <div class="col-md-3">
      <h3><%= link_to "#{artist.name}", artist_path(artist.id) %></h3>
      <h3><em>Genre: <%= link_to "#{artist.genre.name}", genre_path(artist.genre.id) %></em></h3>
    </div>
  <% end %>
</div>

app/views/artists/new.html.erb
<h1>Add a New Artist to <%= @genre.name %></h1>

<%= link_to "Back to #{@genre.name}", genre_path(@genre), class: "btn btn-primary" %>

<br>
<br>

<%= render "form" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %> - <em><%= @genre.name %></em></h1>

<%= link_to "Add New Member", new_artist_member_path(@artist), class: "btn btn-primary" %>

<%= link_to "Add New Review", new_artist_review_path(@artist), class: "btn btn-primary" %>

<%= link_to "Back To #{@genre.name}", genre_path(@genre), class: "btn btn-primary" %>

<%= link_to "Delete #{@artist.name}", artist_path(@artist), :data => {confirm: "Are Your Sure?", method: "delete"}, class: "btn btn-danger" %>

<%= link_to "Update #{@artist.name}", edit_artist_path(@artist), class: "btn btn-warning"%>

<h3>Here are the Members of <%= @artist.name %></h3>

<div class="row">
  <% @artist.members.each do |member| %>
    <div class="col-md-3">
      <h3><%= link_to "#{member.first_name} #{member.last_name}", artist_member_path(@artist, member) %></h3>
    </div>
  <% end %>
</div>

<h3>Here are all of the Reviews for <%= @artist.name %></h3>

<div class="row">
  <% @artist.reviews.each do |review| %>
    <div class="col-md-3">
      <h3><%= review.author %></h3>
      <p><em><%= review.created_at.to_date.to_formatted_s(:long_ordinal) %></em></p>
      <p><%= review.content %></p>

      <%= link_to "Delete", artist_review_path(@artist, review), :data => {confirm: "Are You Sure?", method: "delete"}, class: "btn btn-danger" %>
      <br>
      <br>
    </div>
  <% end %>
</div>

app/views/genres/_form.html.erb
<%= render "layouts/errors", :object => @genre %>

<%= form_for @genre do |f| %>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit genre</h1>

<%= render "form" %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<%= link_to "New Genre", new_genre_path, class: "btn btn-primary" %>

<h3>Here are all the Genres!</h3>

<div class="row">
  <% @genres.each do |genre| %>
    <div class="col-md-3">
      <h3><%= link_to "#{genre.name}", genre_path(genre)%></h3>
    </div>
  <% end %>
</div>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render "form" %>

<br>

<%= link_to "Home", genres_path, class: "btn btn-primary" %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<%= link_to "New Artist", new_genre_artist_path(@genre), class: "btn btn-primary"%>

<%= link_to "Back to Genres", genres_path, class: "btn btn-primary" %>

<%= link_to "Delete", genre_path(@genre), :data => {confirm: "Are Your Sure?", method: "delete"}, class: "btn btn-danger" %>

<%= link_to "Update", edit_genre_path(@genre), class: "btn btn-warning"%>
<h3>Here are all the Artists in this genre!</h3>

<div class="row">
  <% @genre.artists.each do |artist| %>
    <div class="col-md-3">
      <h3><%= link_to "#{artist.name}", artist_path(artist) %></h3>
    </div>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>There was an error. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FanSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "HOME", pages_path, class: "navbar-brand" %></li>
          <li><%= link_to "GENRES", genres_path %></li>
          <li><%= link_to "ARTISTS", artists_path %></li>
          <li><%= link_to "MEMBERS", members_path %></li>
          <li><%= link_to "REVIEWS", reviews_path %></li>

        </ul>
        <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="JK this doesn't work...">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
      </div>
    </div>
  </nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/members/_form.html.erb
<%= render "layouts/errors", :object => @member %>

<%= form_for [@artist, @member] do |f| %>
  <div class="form-group">
    <%= f.label :first_name%>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name%>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :instrument%>
    <%= f.text_field :instrument, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :age%>
    <%= f.text_field :age, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :time_in_band%>
    <%= f.text_field :time_in_band, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/members/edit.html.erb
<h1>Edit member</h1>

<%= render "form" %>

app/views/members/index.html.erb
<h1>Members!</h1>

<h3>Here are all of the recorded band members!</h3>

<div class="row">
  <% @members.each do |member| %>
    <div class="col-md-3">
      <h3><%= link_to "#{member.first_name} #{member.last_name}", artist_member_path(member.artist.id, member.id) %></h3>
      <h3><em>Band: <%= link_to "#{member.artist.name}", artist_path(member.artist.id) %></em></h3>
    </div>
  <% end %>
</div>

app/views/members/new.html.erb
<h1>New Member of <%= @artist.name %></h1>

<%= render "form" %>

app/views/members/show.html.erb
<h1><%= @member.first_name %> <%= @member.last_name %> - <%= @member.age %></h1>

<%= link_to "Back to #{@artist.name}", artist_path(@artist), class: "btn btn-primary" %>

<%= link_to "Delete #{@member.first_name} #{@member.last_name}", artist_member_path(@artist, @member), :data => {confirm: "Are you sure?", method: "delete"}, class: "btn btn-danger" %>

<%= link_to "Update #{@member.first_name} #{@member.last_name}", edit_artist_member_path(@artist, @member), class: "btn btn-warning" %>

<h3><em>In <%= @artist.name %> for <%= @member.time_in_band %> years.</em></h3>

<h3><em><%= @member.instrument %></em></h3>

app/views/reviews/index.html.erb
<h1>Reviews!</h1>

<h3>Here are all of the reviews!</h3>

<div class="row">
  <% @reviews.each do |review| %>
    <div class="col-md-3">
      <h3><%= review.author %></h3>
      <h5><em>Review for: <%= link_to "#{review.artist.name}", artist_path(review.artist.id) %></em></h5>
      <h3><%= review.content %></h3>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<%= render "layouts/errors", :object => @review %>

<h1>Add New Review</h1>

<%= form_for [@artist, @review] do |f| %>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>